//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPreinst.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPreinst.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 txt files (*.txt)|*.txt|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string fileFromat {
            get {
                return ResourceManager.GetString("fileFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功并复制到剪切板 的本地化字符串。
        /// </summary>
        internal static string messageAppendOk {
            get {
                return ResourceManager.GetString("messageAppendOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string messageDelOk {
            get {
                return ResourceManager.GetString("messageDelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式出错 的本地化字符串。
        /// </summary>
        internal static string messageFromatErr {
            get {
                return ResourceManager.GetString("messageFromatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未正确选择必要参数 的本地化字符串。
        /// </summary>
        internal static string messageLoadParamErr {
            get {
                return ResourceManager.GetString("messageLoadParamErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数加载成功 的本地化字符串。
        /// </summary>
        internal static string messageLoadParamOk {
            get {
                return ResourceManager.GetString("messageLoadParamOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未正确选择带问号的SQL语句 的本地化字符串。
        /// </summary>
        internal static string messageLoadSQLErr {
            get {
                return ResourceManager.GetString("messageLoadSQLErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带问号的SQL加载成功 的本地化字符串。
        /// </summary>
        internal static string messageLoadSQLOK {
            get {
                return ResourceManager.GetString("messageLoadSQLOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string messageNotFile {
            get {
                return ResourceManager.GetString("messageNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未输入XML字符串 的本地化字符串。
        /// </summary>
        internal static string messageNotInputXML {
            get {
                return ResourceManager.GetString("messageNotInputXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数文件不存在 的本地化字符串。
        /// </summary>
        internal static string messageNotSqlParam {
            get {
                return ResourceManager.GetString("messageNotSqlParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL文件不存在 的本地化字符串。
        /// </summary>
        internal static string messageNotSqlPath {
            get {
                return ResourceManager.GetString("messageNotSqlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不能为空 的本地化字符串。
        /// </summary>
        internal static string messagePathNotNull {
            get {
                return ResourceManager.GetString("messagePathNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存出错 的本地化字符串。
        /// </summary>
        internal static string messageSaveErr {
            get {
                return ResourceManager.GetString("messageSaveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string messageSaveOk {
            get {
                return ResourceManager.GetString("messageSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作提示 的本地化字符串。
        /// </summary>
        internal static string messageType {
            get {
                return ResourceManager.GetString("messageType", resourceCulture);
            }
        }
    }
}
